
services:
  mysql:
    image: mysql
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: product
    ports:
      - "3308:3306"  # Host port 3307 mapped to container's MySQL port 3306 (Spring Boot connects to 3307)
    volumes:
      - ./mysql_data:/var/lib/mysql  # Correct volume path for MySQL data

  springboot:
    build: .
    container_name: spring_springboot_project
    environment:
      MYSQL_HOST: mysql           # Use the service name 'mysql' as the hostname
      MYSQL_PORT: 3306  # Port 3307 (host-side)
      MYSQL_DB: product           # Database name
      MYSQL_USER: root            # Username
      MYSQL_PASSWORD: root        # Password
    ports:
      - "8082:8080"               # Mapping Spring Boot app port
    depends_on:
      - mysql
