version: '3.8'  # Specify the Docker Compose file format version

services:
  mysql:
    image: mysql:8
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: product
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql  # Use a named volume instead of a relative path
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "mysqldb", "-u", "root", "-p$MYSQL_ROOT_PASSWORD" ]
      interval: 10s
      timeout: 5s
      retries: 3

  springboot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring_springboot_project
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_PORT: 3306
      MYSQL_DB: product
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "8082:8080"
    depends_on:
      mysql:
        condition: service_healthy  # Wait for MySQL to become healthy before starting Spring Boot

volumes:
  mysql_data:  # Named volume for MySQL data persistence
